"""
Base class for trading strategies with standardized interface.
All strategies must inherit from this class and implement required methods.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional, Dict, Any, List
import yaml
from pathlib import Path


class Signal(Enum):
    """Trading signals."""
    HOLD = "HOLD"
    BUY = "BUY"
    SELL = "SELL"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


@dataclass
class MarketData:
    """Single bar of market data."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    symbol: str = ""


@dataclass
class Position:
    """Current position information."""
    direction: str  # "LONG", "SHORT", "NONE"
    quantity: float
    entry_price: float
    entry_time: datetime
    unrealized_pnl: float
    duration_minutes: int


@dataclass
class TradeSignal:
    """Signal generated by strategy."""
    signal: Signal
    quantity: float = 0.0
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""


@dataclass
class BacktestConfig:
    """Configuration for backtesting."""
    initial_capital: float = 10000.0
    commission_rate: float = 0.0006  # 0.06%
    slippage_rate: float = 0.001     # 0.1%
    max_position_size: float = 1.0   # 100% of capital
    
    # Risk management
    max_drawdown_pct: float = 20.0
    daily_loss_limit_pct: float = 5.0
    max_consecutive_losses: int = 5
    
    # Position sizing
    position_sizing_method: str = "fixed"  # "fixed", "percent", "kelly"
    default_position_size: float = 0.1     # 10% of capital
    
    @classmethod
    def from_file(cls, config_path: str) -> 'BacktestConfig':
        """Load configuration from YAML file."""
        with open(config_path, 'r') as f:
            data = yaml.safe_load(f)
        return cls(**data.get('backtest', {}))


class StrategyBase(ABC):
    """
    Base class for all trading strategies.
    
    All strategies must implement:
    1. on_bar() - Process new market data bar
    2. should_enter() - Check for entry conditions
    3. should_exit() - Check for exit conditions
    """
    
    def __init__(self):
        self.name = self.__class__.__name__
        self.parameters = {}
        self.state = {}
        self.indicators = {}
        
        # Initialize strategy
        self._initialize()
    
    @abstractmethod
    def _initialize(self) -> None:
        """Initialize strategy parameters and indicators."""
        pass
    
    @abstractmethod
    def on_bar(self, data: MarketData, position: Position) -> TradeSignal:
        """
        Process new market data bar and generate trading signal.
        
        Args:
            data: Current market data bar
            position: Current position information
            
        Returns:
            TradeSignal indicating what action to take
        """
        pass
    
    def on_trade_opened(self, data: MarketData, entry_price: float, quantity: float, direction: str) -> None:
        """
        Called when a trade is opened.
        Override to implement custom logic (e.g., set stops).
        
        Args:
            data: Market data at trade open
            entry_price: Actual entry price
            quantity: Position size
            direction: "LONG" or "SHORT"
        """
        pass
    
    def on_trade_closed(self, data: MarketData, exit_price: float, pnl: float, direction: str) -> None:
        """
        Called when a trade is closed.
        Override to implement custom logic (e.g., update stats).
        
        Args:
            data: Market data at trade close
            exit_price: Actual exit price
            pnl: Profit/loss from trade
            direction: "LONG" or "SHORT"
        """
        pass
    
    def get_position_size(self, data: MarketData, signal: Signal, capital: float) -> float:
        """
        Calculate position size for trade.
        Override to implement custom position sizing.
        
        Args:
            data: Current market data
            signal: Trading signal
            capital: Available capital
            
        Returns:
            Position size in base currency units
        """
        if hasattr(self, 'position_size_pct'):
            return capital * self.position_size_pct
        return capital * 0.1  # Default 10%
    
    def get_stop_loss(self, data: MarketData, entry_price: float, direction: str) -> Optional[float]:
        """
        Calculate stop loss price.
        Override to implement custom stop loss logic.
        
        Args:
            data: Current market data
            entry_price: Entry price
            direction: "LONG" or "SHORT"
            
        Returns:
            Stop loss price or None
        """
        return None
    
    def get_take_profit(self, data: MarketData, entry_price: float, direction: str) -> Optional[float]:
        """
        Calculate take profit price.
        Override to implement custom take profit logic.
        
        Args:
            data: Current market data
            entry_price: Entry price
            direction: "LONG" or "SHORT"
            
        Returns:
            Take profit price or None
        """
        return None
    
    def update_indicators(self, data: MarketData) -> None:
        """
        Update technical indicators with new data.
        Override to implement custom indicator calculations.
        
        Args:
            data: New market data bar
        """
        pass
    
    def get_parameters(self) -> Dict[str, Any]:
        """Get strategy parameters."""
        return self.parameters.copy()
    
    def set_parameters(self, parameters: Dict[str, Any]) -> None:
        """Set strategy parameters."""
        self.parameters.update(parameters)
    
    def get_state(self) -> Dict[str, Any]:
        """Get current strategy state."""
        return {
            'name': self.name,
            'parameters': self.parameters,
            'state': self.state,
            'indicators': self.indicators
        }
    
    def reset(self) -> None:
        """Reset strategy state for new backtest."""
        self.state = {}
        self.indicators = {}
        self._initialize()


class SimpleMovingAverageStrategy(StrategyBase):
    """
    Example strategy: Simple Moving Average Crossover
    
    Buy when fast MA crosses above slow MA
    Sell when fast MA crosses below slow MA
    """
    
    def _initialize(self) -> None:
        """Initialize strategy parameters."""
        self.parameters = {
            'fast_period': 10,
            'slow_period': 20,
            'position_size_pct': 0.1
        }
        
        self.state = {
            'prices': [],
            'fast_ma': None,
            'slow_ma': None,
            'prev_fast_ma': None,
            'prev_slow_ma': None
        }
    
    def on_bar(self, data: MarketData, position: Position) -> TradeSignal:
        """Process new bar and generate signal."""
        
        # Add price to history
        self.state['prices'].append(data.close)
        
        # Calculate moving averages
        fast_period = self.parameters['fast_period']
        slow_period = self.parameters['slow_period']
        
        if len(self.state['prices']) >= slow_period:
            # Store previous values
            self.state['prev_fast_ma'] = self.state['fast_ma']
            self.state['prev_slow_ma'] = self.state['slow_ma']
            
            # Calculate current values
            self.state['fast_ma'] = sum(self.state['prices'][-fast_period:]) / fast_period
            self.state['slow_ma'] = sum(self.state['prices'][-slow_period:]) / slow_period
            
            # Check for crossover signals
            if (self.state['prev_fast_ma'] is not None and 
                self.state['prev_slow_ma'] is not None):
                
                # Golden cross (buy signal)
                if (self.state['fast_ma'] > self.state['slow_ma'] and 
                    self.state['prev_fast_ma'] <= self.state['prev_slow_ma'] and
                    position.direction == "NONE"):
                    
                    return TradeSignal(
                        signal=Signal.BUY,
                        reason="Fast MA crossed above Slow MA"
                    )
                
                # Death cross (sell signal)
                elif (self.state['fast_ma'] < self.state['slow_ma'] and 
                      self.state['prev_fast_ma'] >= self.state['prev_slow_ma'] and
                      position.direction == "LONG"):
                    
                    return TradeSignal(
                        signal=Signal.CLOSE_LONG,
                        reason="Fast MA crossed below Slow MA"
                    )
        
        return TradeSignal(signal=Signal.HOLD)
    
    def get_position_size(self, data: MarketData, signal: Signal, capital: float) -> float:
        """Calculate position size."""
        return capital * self.parameters['position_size_pct']


class RSIStrategy(StrategyBase):
    """
    Example strategy: RSI Mean Reversion
    
    Buy when RSI < oversold level
    Sell when RSI > overbought level
    """
    
    def _initialize(self) -> None:
        """Initialize strategy parameters."""
        self.parameters = {
            'rsi_period': 14,
            'oversold_level': 30,
            'overbought_level': 70,
            'position_size_pct': 0.05
        }
        
        self.state = {
            'prices': [],
            'gains': [],
            'losses': [],
            'rsi': None
        }
    
    def on_bar(self, data: MarketData, position: Position) -> TradeSignal:
        """Process new bar and generate signal."""
        
        self.state['prices'].append(data.close)
        
        if len(self.state['prices']) > 1:
            # Calculate price change
            change = self.state['prices'][-1] - self.state['prices'][-2]
            
            self.state['gains'].append(max(change, 0))
            self.state['losses'].append(abs(min(change, 0)))
            
            # Calculate RSI
            period = self.parameters['rsi_period']
            if len(self.state['gains']) >= period:
                avg_gain = sum(self.state['gains'][-period:]) / period
                avg_loss = sum(self.state['losses'][-period:]) / period
                
                if avg_loss == 0:
                    self.state['rsi'] = 100
                else:
                    rs = avg_gain / avg_loss
                    self.state['rsi'] = 100 - (100 / (1 + rs))
                
                # Generate signals
                if (self.state['rsi'] < self.parameters['oversold_level'] and
                    position.direction == "NONE"):
                    
                    return TradeSignal(
                        signal=Signal.BUY,
                        reason=f"RSI oversold: {self.state['rsi']:.2f}"
                    )
                
                elif (self.state['rsi'] > self.parameters['overbought_level'] and
                      position.direction == "LONG"):
                    
                    return TradeSignal(
                        signal=Signal.CLOSE_LONG,
                        reason=f"RSI overbought: {self.state['rsi']:.2f}"
                    )
        
        return TradeSignal(signal=Signal.HOLD)
    
    def get_position_size(self, data: MarketData, signal: Signal, capital: float) -> float:
        """Calculate position size."""
        return capital * self.parameters['position_size_pct']